# Generated by Django 4.2 on 2023-04-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='monterguy', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
